SRC_DIR="./svg"
CONF_NEED_CONVERT="YES"
STEP1_FILE="base.svg"
STEP1_OFFSET="0.12"
STEP2_FILE="base_poly_offset.svg"
STEP2_WIDTH="1"
STEP3_FILE="base_isolated.svg"
STEP3_HEIGHT="0.05"
STEP4_FILE="base_isolated.stl"
STEP4_PRUSA_INI="pcb-prusa-2pass.ini"
STEP5_FILE="base_isolated.gcode"
STEP5_FEED="5000"
STEP5_POWER="500"
